export enum CONFIG {
  HEALTH_CHECK = 'HEALTH_CHECK',
  DATABASE_TYPE = 'DATABASE_TYPE',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_DATABASE = 'DATABASE_DATABASE',
  JWT_SETCRET="JWT_SETCRET",
  JWT_EXPIRATION_TIME="JWT_EXPIRATION_TIME"

}

export type ConfigType = {
  [CONFIG.HEALTH_CHECK]: string;
  [CONFIG.DATABASE_TYPE]: string;
  [CONFIG.DATABASE_HOST]: string;
  [CONFIG.DATABASE_PORT]: string;
  [CONFIG.DATABASE_USERNAME]: string;
  [CONFIG.DATABASE_PASSWORD]: string;
  [CONFIG.DATABASE_DATABASE]: string;
  [CONFIG.JWT_SETCRET]: string;
  [CONFIG.JWT_EXPIRATION_TIME]: number;
};
