export enum CONFIG {
  HEALTH_CHECK = 'HEALTH_CHECK',
  DATABASE_TYPE = 'DATABASE_TYPE',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_DATABASE = 'DATABASE_DATABASE',
  JWT_SECRET_CONFIRM_EMAIL = 'JWT_SECRET_CONFIRM_EMAIL',
  JWT_SECRET_AUTH = 'JWT_SECRET_AUTH',
  JWT_SECRET_FRESH_TOKEN = 'JWT_SECRET_FRESH_TOKEN',
  JWT_EXPIRATION_CONFIRM_EMAIL = 'JWT_EXPIRATION_CONFIRM_EMAIL',
  JWT_EXPIRATION_AUTH = 'JWT_EXPIRATION_AUTH',
  JWT_EXPIRATION_FRESH_TOKEN = 'JWT_EXPIRATION_FRESH_TOKEN',
  BCRYPT_ROUND = 'BCRYPT_ROUND',
}

export interface ConfigType {
  [CONFIG.HEALTH_CHECK]: string;
  [CONFIG.DATABASE_TYPE]: string;
  [CONFIG.DATABASE_HOST]: string;
  [CONFIG.DATABASE_PORT]: number;
  [CONFIG.DATABASE_USERNAME]: string;
  [CONFIG.DATABASE_PASSWORD]: string;
  [CONFIG.DATABASE_DATABASE]: string;
  [CONFIG.JWT_SECRET_CONFIRM_EMAIL]: string;
  [CONFIG.JWT_SECRET_AUTH]: string;
  [CONFIG.JWT_SECRET_FRESH_TOKEN]: string;
  [CONFIG.JWT_EXPIRATION_CONFIRM_EMAIL]: string;
  [CONFIG.JWT_EXPIRATION_AUTH]: string;
  [CONFIG.JWT_EXPIRATION_FRESH_TOKEN]: string;
  [CONFIG.BCRYPT_ROUND]: number;
}
